
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://qhiydkgcdnuqmzbpdzut.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFoaXlka2djZG51cW16YnBkenV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NDc4NzMsImV4cCI6MjA1OTUyMzg3M30.sjD76pU_5EWwYJWX1cVx9UAeRs36wRk4f5zKfJCFY2s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
